#!/usr/bin/env bash
# Runs on the HOST via initializeCommand before the container is created or started.
# Idempotent — safe to run on every devcontainer open.
#
# Responsibilities:
#   1. Generate .devcontainer/.env with host-expanded paths (once).
#   2. Compute workspace bind-mount paths.
#   3. Pre-create the Claude persist directory on the host.
#
# Socket permissions are handled by the docker-outside-of-docker feature at
# container startup, so no DOCKER_GID detection is needed here.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_ENV="${SCRIPT_DIR}/.env"

WORKSPACE_ROOT="$(cd "${1:-${SCRIPT_DIR}/..}" && pwd)"
WORKSPACE_BASENAME="$(basename "$WORKSPACE_ROOT")"

ensure_env() {
  local key="$1" value="$2"
  grep -q "^${key}=" "$SHARED_ENV" 2>/dev/null && return 0
  printf '%s=%s\n' "$key" "$value" >> "$SHARED_ENV"
}

upsert_env() {
  local key="$1" value="$2"
  [ -f "$SHARED_ENV" ] && sed -i.bak "/^${key}=/d" "$SHARED_ENV" && rm -f "${SHARED_ENV}.bak"
  printf '%s=%s\n' "$key" "$value" >> "$SHARED_ENV"
}

if [ ! -f "$SHARED_ENV" ]; then
  cat > "$SHARED_ENV" <<EOF
# Generated by .devcontainer/init.sh — do not commit (see .gitignore).

SSH_DIR=${HOME}/.ssh
CLAUDE_PERSIST_HOST_DIR=${HOME}/.devcontainer-claude
DOCKER_SOCK=/var/run/docker.sock
EOF
  echo "[init] Created .devcontainer/.env"
fi

upsert_env LOCAL_WORKSPACE_FOLDER "$WORKSPACE_ROOT"
upsert_env WORKSPACE_FOLDER       "/workspaces/${WORKSPACE_BASENAME}"
echo "[init] workspace → ${WORKSPACE_ROOT} (mounts at /workspaces/${WORKSPACE_BASENAME})"

ensure_env SSH_DIR                 "${HOME}/.ssh"
ensure_env CLAUDE_PERSIST_HOST_DIR "${HOME}/.devcontainer-claude"
ensure_env DOCKER_SOCK             "/var/run/docker.sock"

set -a; source "$SHARED_ENV"; set +a
mkdir -p "${CLAUDE_PERSIST_HOST_DIR}"
